export enum ActionType {
  // global_actions
  OPEN_MODAL = 'OPEN_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  OPEN_WITH_IMG = 'OPEN_WITH_IMG',
  COUPON_CODE = 'COUPON_CODE',

  // prooducts_actions
  GET_PRODUCTS_START = 'GET_PRODUCTS_START',
  GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST',
  GET_BRAND_LIST = 'GET_BRAND_LIST',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR',
  GET_PRODUCT_START = 'GET_PRODUCT_START',
  GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR',
}
